# Generated by Django 4.2 on 2024-10-25 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classes',
            old_name='armor',
            new_name='class_armor',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='desc',
            new_name='class_desc',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='proficiency',
            new_name='class_proficiency',
        ),
        migrations.RenameField(
            model_name='classes',
            old_name='weapons',
            new_name='class_weapons',
        ),
    ]
