# Generated by Django 4.2 on 2024-10-27 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0002_rename_armor_classes_class_armor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alightment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='ArmorType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SpellLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='traits',
            name='alightment_type',
        ),
        migrations.RemoveField(
            model_name='classes',
            name='class_armor',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='spell_level',
        ),
        migrations.AddField(
            model_name='character',
            name='char_alightment',
            field=models.ManyToManyField(related_name='alightment', to='App.alightment'),
        ),
        migrations.AddField(
            model_name='classes',
            name='class_armor',
            field=models.ManyToManyField(related_name='classes', to='App.armortype'),
        ),
        migrations.AddField(
            model_name='spells',
            name='spell_level',
            field=models.ManyToManyField(related_name='spells', to='App.spelllevel'),
        ),
    ]
