# Generated by Django 4.2 on 2024-10-28 12:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0003_alightment_armortype_spelllevel_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_proficiency',
        ),
    ]
