# Generated by Django 4.2 on 2024-10-28 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0004_remove_classes_class_proficiency'),
    ]

    operations = [
        migrations.AddField(
            model_name='armortype',
            name='armor_type',
            field=models.CharField(choices=[('NA', 'No Armor'), ('LA', 'Light Armor'), ('MA', 'Medium Armor'), ('HA', 'Heavy Armor')], default='NA', max_length=30),
        ),
    ]
