# Generated by Django 4.2 on 2024-10-28 14:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0005_armortype_armor_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='classes',
            name='class_armor',
        ),
        migrations.RemoveField(
            model_name='spells',
            name='spell_level',
        ),
        migrations.DeleteModel(
            name='ArmorType',
        ),
        migrations.DeleteModel(
            name='SpellLevel',
        ),
        migrations.AddField(
            model_name='classes',
            name='class_armor',
            field=models.CharField(blank=True, choices=[('No Armor', 'No Armor'), ('Light Armor', 'Light Armor'), ('Medium Armor', 'Medium Armor'), ('Heavy Armor', 'Heavy Armor')], max_length=50),
        ),
        migrations.AddField(
            model_name='spells',
            name='spell_level',
            field=models.CharField(blank=True, choices=[('Cantrip', 'Cantrip'), ('Level 1', 'Level 1'), ('Level 2', 'Level 2'), ('Level 3', 'Level 3'), ('Level 4', 'Level 4'), ('Level 5', 'Level 5'), ('Level 6', 'Level 6'), ('Level 7', 'Level 7'), ('Level 8', 'Level 8'), ('Level 9', 'Level 9')], max_length=30),
        ),
    ]
