# Generated by Django 4.2 on 2024-10-28 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0006_remove_classes_class_armor_remove_spells_spell_level_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classes',
            name='class_armor',
            field=models.CharField(max_length=200),
        ),
    ]
