# Generated by Django 4.2 on 2024-10-28 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0007_alter_classes_class_armor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spells',
            name='spell_level',
            field=models.CharField(max_length=30),
        ),
    ]
