# Generated by Django 4.2 on 2024-10-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0010_remove_spells_spell_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='spells',
            name='spell_level',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
