# Generated by Django 4.2 on 2024-10-29 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0011_spells_spell_level'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='character',
            name='char_alightment',
        ),
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_name',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_spell',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='character',
            name='char_trait',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spell_level',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spell_name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.DeleteModel(
            name='Alightment',
        ),
        migrations.AddField(
            model_name='character',
            name='char_alightment',
            field=models.CharField(default='N', max_length=30),
        ),
    ]
