# Generated by Django 4.2 on 2024-11-21 16:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0013_traits_background_desc_alter_classes_class_armor_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.classes'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_spell',
        ),
        migrations.AlterField(
            model_name='character',
            name='char_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.traits'),
        ),
        migrations.AlterField(
            model_name='classes',
            name='class_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='spells',
            name='spell_desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='traits',
            name='background_desc',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='character',
            name='char_spell',
            field=models.ManyToManyField(to='App.spells'),
        ),
    ]
