# Generated by Django 4.2 on 2024-11-21 17:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0014_alter_character_char_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_trait',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='App.traits'),
        ),
    ]
