# Generated by Django 4.2 on 2024-11-21 17:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('App', '0017_alter_character_char_class_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='character',
            name='char_class',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.classes'),
        ),
        migrations.RemoveField(
            model_name='character',
            name='char_spell',
        ),
        migrations.AlterField(
            model_name='character',
            name='char_trait',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='App.traits'),
        ),
        migrations.AddField(
            model_name='character',
            name='char_spell',
            field=models.ManyToManyField(to='App.spells'),
        ),
    ]
